version: "3.4"

services:
  gateway:
    image: traefik:v2.4
    ports:
      - 10000:10000
      - 8080:8080
    networks:
      - internal_net
      - frontend
    volumes:
      - ../gateway/traefik.toml:/etc/traefik/traefik.toml
      - ../gateway:/srv/gateway/:rw
      - /var/run/docker.sock:/var/run/docker.sock

  policies:
    image: openpolicyagent/opa
    ports:
      - 8181:8181
    command:
      - "run"
      - "--server"
      - "--log-level=debug"
      - "--skip-version-check"
      - "api_authz.rego"
    volumes:
      - ../policy/api_authz.rego:/api_authz.rego
    networks:
      - internal_net
    depends_on:
      - gateway

  fastapi_service:
    build:
      dockerfile: docker/fastapi.dockerfile
      context: ..
    environment:
      MODULE_NAME: fastapi_main
      PORT: 8080
      CERTFILENAME: fastapi_service.pem
      KEYFILENAME: fastapi_service-key.pem
    networks:
      - internal_net
    expose:
      - 8080
    depends_on:
      - gateway
    volumes:
      - ../gateway:/srv/gateway

  auth_service:
    build:
      dockerfile: docker/fastapi.dockerfile
      context: ..
    environment:
      MODULE_NAME: auth_main
      PORT: 8090
      CERTFILENAME: auth_service.pem
      KEYFILENAME: auth_service-key.pem
    networks:
      - internal_net
    expose:
      - 8090
    depends_on:
      - gateway
    volumes:
      - ../gateway:/srv/gateway

networks:
  frontend:
    driver: bridge

  internal_net:
    internal: true
